CREATE TABLE IF NOT EXISTS application_settings (
  setting_key VARCHAR(128) NOT NULL PRIMARY KEY,
  value_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
